name = "twitcasting-discord-webhook"
compatibility_date = "2024-09-21"
compatibility_flags = [ "nodejs_compat" ]
tail_consumers = [{service = "twitcasting-discord-webhook-tail"}]

[observability]
enabled = true

[[kv_namespaces]]
binding = "WATCH_LIST"
id = "2ccff9a8459c4d179a477d068ec8cdb9"
